### ISSUE TITLE
LoggerExample bug when logging with csv files on linux

### ISSUE THREAD

**Issue by wonwon0** [inertialsense/inertial-sense-sdk#16]
I ran it on Linux, haven't verified on windows.

when building then running with the following parameters:
`./ISLoggerExample /dev/ttyUSB0 csv`

The logging starts but A LOT of ".csv" files are generated with each a single row of data in it.
Weirdly, this bug does not happen if there is a ".dat" file in the IS_log directory (from prior logging for example). Datas are logged in a single ".csv" file until it becomes a bit big then an other is created, with the suffix 0002 for example (as expected).

Picture of a small fraction of the files created with less than 1 sec of data logging.
![image](https://user-images.githubusercontent.com/22689509/67865402-98477300-fafd-11e9-97ed-2248ad593d2b.png)

**Comment by wonwon0** [comment]
Sorry for the tree issues created back to back but i felt these were separate issues. I didn't want to spam.

**Comment by wonwon0** [comment]
It seems the bug is not present when i run it in Clion.
When i execute it as show in the first post (in the terminal) the bug is present.

**Comment by siddirp** [comment]
@wonwon0 Did you modify the example at all?
