### ISSUE TITLE
Firmware Update from Evaltool brick

### ISSUE THREAD

**Issue by manderino1** [inertialsense/inertial-sense-sdk#165]
Hi, we updated a rugged uINS, dual GNSS, from Evaltool v1.8.5 and, after it, the INS disappeared from the available devices
There is no sign of life when connecting it to the computer, no COM detected in device management

Is this a known problem? There is any known procedure to reflash firmware from this situation and unbrick the ins?
Thank you

**Comment by siddirp** [comment]
Marco, I will email you directly. Thanks.
