### ISSUE TITLE
LoggerExample does not log expected data on linux

### ISSUE THREAD

**Issue by wonwon0** [inertialsense/inertial-sense-sdk#17]
When commenting line 52 of the example:
`inertialSense.BroadcastBinaryDataRmcPreset(RMC_PRESET_INS_BITS);`

and un-commenting line 55 of the example:
`inertialSense.BroadcastBinaryData(DID_DUAL_IMU, 10); // imu every 10 milliseconds (100 hz)`

The data that is logged is:
![image](https://user-images.githubusercontent.com/22689509/67864111-7ea52c00-fafb-11e9-869b-e2809f253d2d.png)

When modifying the code, for example changing the data type to be logged:
`inertialSense.BroadcastBinaryData(DID_DUAL_IMU_MAG, 10); // imu every 10 milliseconds (100 hz)`

The same data types as shown in the previous picture are logged and the "DID_DUAL_IMU_MAG" data is not present at all.

**Comment by wonwon0** [comment]
Sorry for the tree issues created back to back but i felt these were separate issues. I didn't want to spam.

**Comment by waltjohnson** [comment]
Hi @wonwon0.  Did you get this issue resolved?  Can we close this issue?
