### ISSUE TITLE
EvalTool_1.8.5.deb license?

### ISSUE THREAD

**Issue by FabioLolix** [inertialsense/inertial-sense-sdk#177]
Hi, the EvalTool_1.8.5.deb package don't have any license inside

**Comment by waltjohnson** [comment]
Hi Fabio,

We have added the following license to our EvalTool.deb which will go out in the next software release in Q1 of this year.  In the meantime, you can refer to this LICENSE file:

https://github.com/inertialsense/inertial-sense-sdk/blob/master/LICENSE

Regards,
Inertial Sense Support
