### ISSUE TITLE
using namespace std in InertialSense.h

### ISSUE THREAD

**Issue by FloopCZ** [inertialsense/inertial-sense-sdk#239]
Hi, the `InertialSense.h` header has `using namespace std` directive which causes a lot of collisions when included in a larger code base. It is not a good practice to globally publish namespaces, would it be possible to get rid of it?

**Comment by waltjohnson** [comment]
We should be able accommodate this change.

**Comment by FloopCZ** [comment]
Great! Also, a namespace wrapping the whole InertialSense library would be great to avoid collisions, but we can live without it. :-)

**Comment by FloopCZ** [comment]
Thank you for fixing in 1.8.7!
