### ISSUE TITLE
Using an RTOS

### ISSUE THREAD

**Issue by rgburrill** [inertialsense/inertial-sense-sdk#26]
Does anyone have any example task setting up communication through an RTOS?  I would like to use the Arduino comm example but as one task providing data to be used by another system.

**Comment by waltjohnson** [comment]
Hi @rgburrill.  Do you still need help with this?  Can you clarify your question?  

Have you seen our Arduino example project file?

**Comment by rgburrill** [comment]
I have seen your example which is why I reference it.  But it is a standalone program, not an RTOS task.  It is also for the Arduino and has some, I assume, Arduino specific functions.  For example, initializing the serial channels with Serial.begin and Serial1.begin is never explained anywhere.

 

This INS seems very well suited for embedded applications and, as such, has or will interface regularly with embedded real-time operating systems.  You provide examples of how to interface stand alone and with Linux, Mac and Windows but none of the are true real-time, nor small footprint, like an embedded RTOS.

**Comment by waltjohnson** [comment]
See our EVB-2 embedded RTOS example project.  The project is open source for our EVB-2, which runs on a SAME70 ARM Cortex M7 processor running an RTOS and uses the inertial-sense-sdk library for communications with the uINS.

https://github.com/inertialsense/inertial-sense-sdk/tree/release/EVB-2

**Comment by rgburrill** [comment]
Looks like just what I need.  Nice timing.

**Comment by rgburrill** [comment]
Thank you so much.
