### ISSUE TITLE
Configuration to have RTK position & RTK compassing

### ISSUE THREAD

**Issue by AlexisTM** [inertialsense/inertial-sense-sdk#32]
Hi,

What happens when we enable both compassing & RTK with an NTRIP input?
* Compassing with moving baseline with GPS1 & GPS2 & Positioning with GPS1 & NTRIP 
* Or does it do Positioning of both GPS1-NTRIP and GPS2-NTRIP and compassing on the resulting poses

```
-flashconfig=RTKCfgBits=0x9
RTKCfgBits |= RTK_CFG_BITS_ROVER_MODE_RTK_POSITIONING;
RTKCfgBits |= RTK_CFG_BITS_ROVER_MODE_RTK_COMPASSING;
```

**Comment by siddirp** [comment]
@AlexisTM Our latest firmware has error checking to prevent turning them both on. However, in any setup, you should not enable both. Only one can run at a time.
