### ISSUE TITLE
Two units with identical configuration gives different results

### ISSUE THREAD

**Issue by AlexisTM** [inertialsense/inertial-sense-sdk#33]
I have two µINS3 device, one is the rugged version, one is in the EVB-2. 

I have both connected via USB (the EVB-2 connected to the µINS3 port)
* Identical parameters (except the slight difference in antenna position)
* Identical distance between the antennas (1m)
* Identical movements/conditions (both installed on a single wooden plate)
* Identical firmware
* Identical NTRIP connection

Regardless of that similarity, the EVB-2 gets the RTK fix or compassing fix, while the rugged µINS3 doesn't. I tried to get the fix on the µINS3 and couldn't while in the middle of the park with a clear sky. 
What am I missing? 

**µINS3 config dump**

```
DID_DEV_INFO: SN40840, Fw 1.8.2.0 r4, 2020-07-30 16:49:57, Proto 1.2.96.8

Current flash config
cBrdConfig = 1083062272
checksum = 3923660164
gnssSatSigConst = 4924
gps1AntOffset[0] = 0
gps1AntOffset[1] = -0.524999976
gps1AntOffset[2] = 0
gps2AntOffset[0] = 0
gps2AntOffset[1] = 0.524999976
gps2AntOffset[2] = 0
gpsMinimumElevation = 0.261799395
gpsTimeSyncPeriodMs = 1000
insDynModel = 8
insOffset[0] = 0
insOffset[1] = 0
insOffset[2] = 0
insRotation[0] = 0
insRotation[1] = 0
insRotation[2] = 0
ioConfig = 4384
key = 26
lastLla[0] = 50.852697999999997
lastLla[1] = 4.3144577999999996
lastLla[2] = 72.048000000000002
lastLlaTimeOfWeekMs = 387231200
lastLlaUpdateDistance = 1000
lastLlaWeek = 2117
magDeclination = 0
magInclination = 0
refLla[0] = 50.852638310854672
refLla[1] = 4.3145834288500904
refLla[2] = 92.910544845275581
reserved = 0
RTKCfgBits = 524296
sensorConfig = 15
ser0BaudRate = 921600
ser1BaudRate = 921600
size = 240
startupGPSDtMs = 200
startupImuDtMs = 1
startupNavDtMs = 4
sysCfgBits = 4127
wheelConfig.bits = 0
wheelConfig.diameter = 0
wheelConfig.distance = 0
wheelConfig.e_i2l[0] = 0
wheelConfig.e_i2l[1] = 0
wheelConfig.e_i2l[2] = 0
wheelConfig.t_i2l[0] = 0
wheelConfig.t_i2l[1] = 0
wheelConfig.t_i2l[2] = 0
zeroVelOffset[0] = 0
zeroVelOffset[1] = 0
zeroVelOffset[2] = 0
zeroVelRotation[0] = 0
zeroVelRotation[1] = 0
zeroVelRotation[2] = 0
```

**EVB-2 config dump**

```python
DID_DEV_INFO: SN40756, Fw 1.8.2.0 r4, 2020-07-30 16:49:57, Proto 1.2.96.8

Current flash config
cBrdConfig = 1083062272
checksum = 3757573147
gnssSatSigConst = 4924
gps1AntOffset[0] = 0
gps1AntOffset[1] = 0.589999974
gps1AntOffset[2] = 0
gps2AntOffset[0] = 0
gps2AntOffset[1] = -0.409999996
gps2AntOffset[2] = 0
gpsMinimumElevation = 0.261799395
gpsTimeSyncPeriodMs = 1000
insDynModel = 8
insOffset[0] = 0
insOffset[1] = 0
insOffset[2] = 0
insRotation[0] = 0
insRotation[1] = 0
insRotation[2] = 0
ioConfig = 4384
key = 26
lastLla[0] = 50.852691299999996
lastLla[1] = 4.3146163
lastLla[2] = 86.962000000000003
lastLlaTimeOfWeekMs = 295462400
lastLlaUpdateDistance = 1000
lastLlaWeek = 2117
magDeclination = 0
magInclination = 0
refLla[0] = 50.852638310854672
refLla[1] = 4.3145834288500904
refLla[2] = 92.910544845275581
reserved = 0
RTKCfgBits = 524296
sensorConfig = 15
ser0BaudRate = 921600
ser1BaudRate = 921600
size = 240
startupGPSDtMs = 200
startupImuDtMs = 1
startupNavDtMs = 4
sysCfgBits = 4127
wheelConfig.bits = 0
wheelConfig.diameter = 0
wheelConfig.distance = 0
wheelConfig.e_i2l[0] = 0
wheelConfig.e_i2l[1] = 0
wheelConfig.e_i2l[2] = 0
wheelConfig.t_i2l[0] = 0
wheelConfig.t_i2l[1] = 0
wheelConfig.t_i2l[2] = 0
zeroVelOffset[0] = 0
zeroVelOffset[1] = 0
zeroVelOffset[2] = 0
zeroVelRotation[0] = 0
zeroVelRotation[1] = 0
zeroVelRotation[2] = 0
```

**Comment by siddirp** [comment]
@AlexisTM - Your other question indicated you were trying to use Compassing and RTK positioning simultaneously. Is this the case in this setup? To discuss further could you send an email to support@inertialsense.com.

**Comment by AlexisTM** [comment]
In this setup, it was either one or the other, the firmware [1.8.2] correctly disabled POSITION if I tried to enabled 0x09.

In this case, the `RTKCfgBits` are 0x80008

**Comment by AlexisTM** [comment]
@siddirp 
The µINS3 is from the µINS Dual GNSS Compass Development Kit

**Comment by siddirp** [comment]
Are you seeing "Compassing Fix" status? Most likely you have interference
problems and aren't completely getting into a fixed state.


[image: Inertial Sense] <http://www.inertialsense.com/>
*Andrew Priddis*
*Sr Systems Engineer*
andrew.priddis@inertialsense.com
*inertialsense.com* <http://www.inertialsense.com/>

**Comment by AlexisTM** [comment]
Both the rugged unit and the EVB-2 should be having the same perturbations, yet no received satellite goes into Float/Fix state at all on the rugged unit, even in ideal situation (open-sky, open-field). I go not a single GPS signal to Float/Fix for both compassing and position mode on the rugged unit.

**Comment by siddirp** [comment]
What does mems precision and calibration look like in 2020?

View in browser (https://info.inertialsense.com/e2t/sc2/Mm-nFbkB_0QW7cKx4l7tV6QgW7mFN9g8QqZWMW8hWtXD8QqH96f1HVPN203 )

Inertial Sense (https://info.inertialsense.com/e2t/sc2/Mm-nFbkB_0QW7cKx4l7tV6QgW7mFN9g8QqZWMW8hWtXD8QqH96f1HVPN213 )

The Tiny Sensor with Giant Capabilities

What could your device do with this kind of power?

IS Sensor Datasheet (https://info.inertialsense.com/e2t/sc2/Mm-nFbkB_0QW7cKx4l7tV6QgW7mFN9g8QqZWMW8hWtXD8QqH96f1HVPN223 )

IMU Datasheet

Your device deserves high precision and quick telemetry without being weighed down. Check out our Datasheet and see if our sensors meet your specifications.

Download Datasheet (https://info.inertialsense.com/e2t/sc2/Mm-nFbkB_0QW7cKx4l7tV6QgW7mFN9g8QqZWMW8hWtXD8QqH96f1HVPN233 )

"Inertial Sense has developed a disruptive technology. It is going to change everything about our industry."

- AUVSI Judges, 2019

View Products (https://info.inertialsense.com/e2t/sc2/Mm-nFbkB_0QW7cKx4l7tV6QgW7mFN9g8QqZWMW8hWtXD8QqH96f1HVPN243 )

Schedule Meeting (https://info.inertialsense.com/e2t/sc2/Mm-nFbkB_0QW7cKx4l7tV6QgW7mFN9g8QqZWMW8hWtXD8QqH96f1HVPN253 )

Read Blog Posts (https://info.inertialsense.com/e2t/sc2/Mm-nFbkB_0QW7cKx4l7tV6QgW7mFN9g8QqZWMW8hWtXD8QqH96f1HVPN263 )

Inertial Sense, 384 S 400 W #125th, Lindon, UT 84042, USA, 801-610-6771

Unsubscribe (https://info.inertialsense.com/hs/manage-preferences/unsubscribe-all?d=VnBg1c6WzZmnW2p76LK3-1rCSW3X_fKX21hrytW1Ztq4c1XmmZlW1Synkn3W3636W3HbJ363KbsvFW3R0gs93_-09-W47szjy45RlhdW3P28X24hCPvhW43T2P-7DvMj2W17f7hv8zMnRfW4Rc5GT6tf82_W4_ZJwY8YNKs3V28Q_q8Xp6wxMGKd_P20N5RW3PHcCm8jR_5YW3d2RgN2R0wzY4CplG1&v=3&_hsenc=p2ANqtz-_G8dTM7_HFH_QfvWhL2TyRlpfVdmR2lgsweaDN5JGDD-hR_GGefETepYRXvc1xK93ZpW4HmtXP3-bT_DHvQ3UY4LZ4X13d3MFOtN5YrzqaOySqS23OFo-xDWfiMCb74pfzruSxlQ231QtC2TYKkjE-g26HRw&_hsmi=86142041 )

Manage preferences (https://info.inertialsense.com/hs/manage-preferences/unsubscribe?d=VnBg1c6WzZmnW2p76LK3-1rCSW3X_fKX21hrytW1Ztq4c1XmmZlW1Synkn3W3636W3HbJ363KbsvFW3R0gs93_-09-W47szjy45RlhdW3P28X24hCPvhW43T2P-7DvMj2W17f7hv8zMnRfW4Rc5GT6tf82_W4_ZJwY8YNKs3V28Q_q8Xp6wxMGKd_P20N5RW3PHcCm8jR_5YW3d2RgN2R0wzY4CplG1&v=3&_hsenc=p2ANqtz-_G8dTM7_HFH_QfvWhL2TyRlpfVdmR2lgsweaDN5JGDD-hR_GGefETepYRXvc1xK93ZpW4HmtXP3-bT_DHvQ3UY4LZ4X13d3MFOtN5YrzqaOySqS23OFo-xDWfiMCb74pfzruSxlQ231QtC2TYKkjE-g26HRw&_hsmi=86142041 )

**Comment by waltjohnson** [comment]
Alexis.  Have you made any progress on this issue?

**Comment by AlexisTM** [comment]
On the last in-field tests, I finally got similar results but the ambiguity resolution ratio never went higher than 2 or so for both units.

**Comment by waltjohnson** [comment]
I suspect there is some sort of interference.  This can be due to mutli-pathing of the satellite signals or some other noise source that is impacting the RTK solution.  Are you using [GPS antenna ground planes](https://docs.inertialsense.com/user-manual/gnss/gnss_antennas/#gnss-antenna-ground-plane)?  What is the distance between your antennas?

**Comment by AlexisTM** [comment]
I am not currently using a ground plane, I will add one on each antenna.

The distance between antennas is 1m for both.

**Comment by siddirp** [comment]
What does mems precision and calibration look like in 2020?

Inertial Sense (https://info.inertialsense.com/e2t/sc2/MmZ-8yjZ5PLW8YKH3_7DqBsHW6xgdls7sc4ZSV28PGW7Zp2pWdBzP8M04 )

The Guide to Choosing A Sensor

Which sensor make sense for your project?

Sensor Buying Cheat Sheet (https://info.inertialsense.com/e2t/sc2/MmZ-8yjZ5PLW8YKH3_7DqBsHW6xgdls7sc4ZSV28PGW7Zp2pWdBzP8N04 )

Sensor Buying Cheat Sheet

At this point, you might be wondering where to start when shopping for a sensor for your project. Deciding between an IMU, AHRS, or GNNS & RTK can be difficult. We've made this handy guide to help answer some basic questions quickly.

Read Blog Post (https://info.inertialsense.com/e2t/sc2/MmZ-8yjZ5PLW8YKH3_7DqBsHW6xgdls7sc4ZSV28PGW7Zp2pWdBzP8P04 )

"Inertial Sense has developed a disruptive technology. It is going to change everything about our industry."

- AUVSI Judges, 2019

View Products (https://info.inertialsense.com/e2t/sc2/MmZ-8yjZ5PLW8YKH3_7DqBsHW6xgdls7sc4ZSV28PGW7Zp2pWdBzP8Q04 )

Schedule Meeting (https://info.inertialsense.com/e2t/sc2/MmZ-8yjZ5PLW8YKH3_7DqBsHW6xgdls7sc4ZSV28PGW7Zp2pWdBzP8R04 )

Read Blog Posts (https://info.inertialsense.com/e2t/sc2/MmZ-8yjZ5PLW8YKH3_7DqBsHW6xgdls7sc4ZSV28PGW7Zp2pWdBzP8S04 )

Inertial Sense, 384 S 400 W #125th, Lindon, UT 84042, USA, 801-610-6771

Unsubscribe (https://info.inertialsense.com/hs/manage-preferences/unsubscribe-all?d=VnzSyB6WzZmnW2p76LK3-1rCSW3X_fKX21hrytW1Ztq4c1XmmZlW1Synkn3W3636W3HbJ363KbsvFW3R0gs93_-09-W47szjy45RlhdW3P28X24hCPvhW43T2P-7DvMj2W15gBJz5wqwC8W64QbLK4RszpdW505_f17XxhwGVWzpl95Sb1gvMXk_7QbwcydW8d8krT3fLFQvW2DzBP36Z0BCz3pWY2&v=3&_hsenc=p2ANqtz-_f4UQozYw1EWzpvuOgweL1o_2wir4tOAN9d0XfrQMkpe8lVIivgFYsQQ2Tmemkx7ecZz5FPmZFif2TPybrA9ULylL1mqZ2i0iovLaD32snsOQMXI6j4tG_jSNjlkwqJozAnAJ9PrB9FVwH5t8P51RFWqcpcw&_hsmi=86142139 )

Manage preferences (https://info.inertialsense.com/hs/manage-preferences/unsubscribe?d=VnzSyB6WzZmnW2p76LK3-1rCSW3X_fKX21hrytW1Ztq4c1XmmZlW1Synkn3W3636W3HbJ363KbsvFW3R0gs93_-09-W47szjy45RlhdW3P28X24hCPvhW43T2P-7DvMj2W15gBJz5wqwC8W64QbLK4RszpdW505_f17XxhwGVWzpl95Sb1gvMXk_7QbwcydW8d8krT3fLFQvW2DzBP36Z0BCz3pWY2&v=3&_hsenc=p2ANqtz-_f4UQozYw1EWzpvuOgweL1o_2wir4tOAN9d0XfrQMkpe8lVIivgFYsQQ2Tmemkx7ecZz5FPmZFif2TPybrA9ULylL1mqZ2i0iovLaD32snsOQMXI6j4tG_jSNjlkwqJozAnAJ9PrB9FVwH5t8P51RFWqcpcw&_hsmi=86142139 )

**Comment by waltjohnson** [comment]
@AlexisTM Hi Alex.  Did this get resolved?  Did you add antenna ground planes fix your problem?

**Comment by AlexisTM** [comment]
I added the ground planes, which indeed improved the GPS signal. 

Yet, I could not get an RTK fix nor robust RTK compassing, with the ambiguity resolution ratio never reaching over 1 or 2. 
When compassing (baseline of 1m), the measured distance was oscillating from 0.6m to 1.8m.

Here-under, the top plots are from the µINS3 (top left) and EVB-2 (top right). The data comes from `DID_INS_1` and is converted to from NED to ENU. The bottom (orange) plot is from our reference. 

![Comparison of X-Y estimation](https://user-images.githubusercontent.com/6976744/91275766-e1e60600-e780-11ea-922a-d226ee829e85.png)

Here-under, the `GPS_POS_1` position output from the EVB-2 (pink), the µINS3 (purple) and our reference (yellow) for the same track. The graph looks stretched on the x-axis as it is longitude & latitude.

![Comparison of Lat-Lon](https://user-images.githubusercontent.com/6976744/91276167-70f31e00-e781-11ea-969b-d677eb123487.png)

We can see one big jumps of position in the estimation for the µINS3 and a very very bad estimation for the EVB-2.

It is to note that the yaw (heading) of the EVB-2 was far (20°) from the estimation from both the µINS, our reference and a competitor with at worse almost 30° off. This can easily explain the bad EKF output.

**Comment by waltjohnson** [comment]
Hi @AlexisTM.  Are these logs recorded with RTK positioning or RTK compassing mode enabled?  If the AR ratio is below 3 you will likely have RTK problems.  If you have ground planes under the GPS antennas and are still having issues, I would suspect you are getting interference from other objects in close proximity.  What is the the GPS satellite CNO level?  This should be above 40 dBHz for RTK.

https://docs.inertialsense.com/user-manual/troubleshooting/gnss/#satellite-cno-strength-rfi-and-emi

Any chance you can record PPD (post process data) log?  This will gives us best visibility into issues you are seeing. 

https://docs.inertialsense.com/user-manual/logging-plotting/data_logging/#post-process-data-ppd-logging-instructions

**Comment by AlexisTM** [comment]
As I could not get a proper fix, this was without RTK and without compassing (Same condition as the reference).
