### ISSUE TITLE
Where are the Python scripts located?

### ISSUE THREAD

**Issue by AlexisTM** [inertialsense/inertial-sense-sdk#34]
There are few mentions of 2 python scripts to analyze logs:
* LogInspector.py
* LogPlotter.py

Where are these located?

**Comment by waltjohnson** [comment]
Hi Alexis.  See the latest version of our SDK for these scripts.

https://github.com/inertialsense/inertial-sense-sdk/tree/release/python/logInspector

**Comment by AlexisTM** [comment]
Thanks!
