### ISSUE TITLE
Mixed tabs and spaces makes code hard to read.

### ISSUE THREAD

**Issue by fdkz** [inertialsense/inertial-sense-sdk#482]
A lot of code has mixed tabs and spaces, and also uses tabs for alignment. As tabs are already used, I kindly suggest using tabs everywhere only for indenting, and spaces for alignment, as explained here:
https://dmitryfrank.com/articles/indent_with_tabs_align_with_spaces

Currently much of the code is quite hard to read for a lot of people in most editors and command-line tools. Example from src/data_sets.h:

![image](https://github.com/inertialsense/inertial-sense-sdk/assets/1922973/ba536241-faea-47d3-b341-730be5919ee4)

**Comment by andrewpriddis** [comment]
Our codebase has grown significantly over time and we have slowly been
replacing tabs with spaces as appropriate in our work. Thank you for your
feedback. In the meantime, most modern code editors will fully format a
file for you which you can use for your convenience until the full
conversion is completed.


[image: Inertial Sense] <http://www.inertialsense.com/>
*Andrew Priddis*
*Sr Systems Engineer*
***@***.***
*inertialsense.com* <http://www.inertialsense.com/>

**Comment by kylemallory** [comment]
@fdkz Thanks for your feedback in this area.  We share your sentiment.  Fortunately, we've been making of a number of large refactors working toward the 2.3.0 feature release.  In this effort, we have gone through and done a complete white-space refactor on the entire SDK code-base, standardizing on 4-spaces for indents, and ensuring things column align, etc.

I am going to close this issue, as the work has been done on the 'develop' branch, but it will be a couple months before the 2.3.0 release.  If you have any questions or further issue, please feel free to open another issue.
