### ISSUE TITLE
Maximum of 3 CAN messages

### ISSUE THREAD

**Issue by matheuskbc** [inertialsense/inertial-sense-sdk#502]
Hello,

I am executing some tests with the CAN bus in an IMX-5. I would like to read IMU data (accelerometers + gyros) plus the INS orientation solution (I am particularly interested in yaw). However, I am able to send only 3 CIDs at the same time via the CAN bus. Is this a limit? Is there a way to send 4 messages ? 

My config:

    1. CAN bus baudrate set to 250 kbps
    2. IMU: RUG-3-IMX.G0
    3. Messages that I want to receive:
    4. CID_DUAL_PX, CID_DUAL_QY, CID_DUAL_PX, CID_DUAL_RZ and CID_INS_EULER
    5. 0x5A, 0x5B, 0x5C and 0x5D as ids of the CAN messages above

Best regards

Matheus

**Comment by andrewpriddis** [comment]
Hi Matheus,
The processor on the current IMX-5 limits the number of CAN messages that can be sent. It is a hardware issue that we will address in our next hardware release of the IMX-5.1. In the meantime, if you stream messages more slowly you can receiver more types of messages.
