### ISSUE TITLE
EvalTool 2.0.1 firmware update does not finish

### ISSUE THREAD

**Issue by honzov** [inertialsense/inertial-sense-sdk#558]
![eval_bug](https://github.com/inertialsense/inertial-sense-sdk/assets/34425345/e7d08fcb-9fc2-4794-a9ad-91c373f712e8)

When downloading new 2.0.1 EvalTool and trying to upgrade firmware to 2.0.1 the process never finishes.

**Comment by kylemallory** [comment]
@honzov The uINS-3.2 has reached End-of-Life status and is no longer supported with the new 2.x firmware. The latest, and last release supporting the uINS-3.2 is firmware 1.11.2.

Additionally, updating the IMX using the Firmware Package is currently not supported (this is an active priority for us).  If you have an IMX-5 that you'd like to update, please click "FwPkg" and choose the "IMX" option, and then select the IMX-5 firmware image.

Additionally, I have created an internal issue to improve the error messaging on the Firmware Update dialog to correctly reflect the error/unsupported device.  Thank you.
