### ISSUE TITLE
Setting serial port to low latency

### ISSUE THREAD

**Issue by shrijitsingh99** [inertialsense/inertial-sense-sdk#591]
In the VectorNav drivers which I have used in the past, there was a method to set the serial port to use low latency mode.
You can see the discussion here: https://github.com/dawonn/vectornav/pull/82

Can something like that potentially be useful for the inertial sense driver too?

**Comment by andrewpriddis** [comment]
We provide what we call RMC messages. See this information: https://docs.inertialsense.com/user-manual/com-protocol/isb/#realtime-message-controller-rmc
