### ISSUE TITLE
cltool -reset on 1.11.2 is stuck

### ISSUE THREAD

**Issue by honzov** [inertialsense/inertial-sense-sdk#598]
![image](https://github.com/inertialsense/inertial-sense-sdk/assets/34425345/b2460d13-12f4-43a5-b8ac-2a2ddd0719b5)

I've upgraded firmware and sdk version to 1.11.2 (Linux). After calling software reset from cltool, it gets stuck and needs to be interrupted. Also the device is not freed after the interruption. 

Maybe I did something wrong, but I don't know what. From EvalTool gui (Win) reset works fine. Can you maybe take a look at it and tell me how I should proceed? Thanks!

**Comment by andrewpriddis** [comment]
@honzov - this was fixed and merged into the develop branch.
