### ISSUE TITLE
libusb error when buidling cltool and Examples 

### ISSUE THREAD

**Issue by andrewjlock** [inertialsense/inertial-sense-sdk#622]
I am trying to run some IMX-5 units (and hopefully soon some IG-2-IMX-5s) on Raspberry Pis (model 5) running Ubuntu 24.04 server.

I can build the parent SDK library successfully. But when I try and build the `cltool` or `ExampleProjects` libraries I get errors relating to `libusb`  such as: 
``` 
undefined reference to `libusb_init'
undefined reference to `libusb_close'
undefined reference to `libusb_exit'
```
As far as I can tell, I have followed the Ubuntu-latest continuous integration workflow exactly, and installed the required dependencies. I plan to run the sensors with ROS , but wanted to check integration with the CL tool first. I have tried in vein to include the `libusb` package in the CL tool `CMakeLists.txt` - but I admit I am not particularly experienced in building complex C++ projects.

Do you have any advice how to get this running? Thanks.

**Comment by andrewpriddis** [comment]
You need to pull the submodules. libusb is one of them. git submodule update --init --recursive

**Comment by andrewjlock** [comment]
Ah, thank you very much for the prompt response. This has resolved it.

I had overlooked submodules, thinking the issue was with the system libusb installation.
